export const CONVERSATION_MIN_WIDTH = 520
export const ARTIFACT_SIDECAR_MIN_WIDTH = 320
export const ARTIFACT_SIDECAR_MAX_WIDTH = 1200
export const ARTIFACT_SIDECAR_DESKTOP_BREAKPOINT = 1200
export const ARTIFACT_SIDECAR_MAX_VIEWPORT_FRACTION = 0.56
export const ARTIFACT_SIDECAR_OVERLAY_VIEWPORT_FRACTION = 0.92
