import { FileState } from '../types/files'

export const initialState: FileState = {
  viewerCapabilities: {},
  viewerCapabilityRequests: {},
  reprocessingRequests: {},
  files: [],
  folders: [],
  loading: false,
  error: null,
  selectedTags: [],
  isModalOpen: false,
  filename: '',
  foldername: '',
  jobStatuses: {},
  pollingLoading: false,
  searchQuery: '',
  selectedItems: [],
  isMoveModalOpen: false,
  mediaTypeFilter: 'all',
  sharedFiles: [],
  sharedFilesLoading: false,
  sharedFilesError: null,
  shareModalFileId: null,
  shareModalFileName: '',
  visionModels: null,
  visionModelsError: null,
}
