import { FileState } from '../types/files'

export const initialState: FileState = {
  files: [],
  folders: [],
  loading: false,
  error: null,
  selectedTags: [],
  isModalOpen: false,
  filename: '',
  foldername: '',
  expandedFolders: {},
  jobStatuses: {},
  pollingLoading: false,
  searchQuery: '',
  selectedItems: [],
  currentView: 'files',
  isMoveModalOpen: false,
  mediaTypeFilter: 'all',
  sharedFiles: [],
  sharedFilesLoading: false,
  sharedFilesError: null,
  activeTab: 'my-files',
  shareModalFileId: null,
  shareModalFileName: '',
  visionModels: null,
  visionModelsError: null,
}
