import {
  type WorkflowBuilderState,
  SavingStatus,
  OutputDisplayMode,
} from '../types/workflowBuilder'
import { INITIAL_NODES, INITIAL_EDGES } from '@/utils/constants/workflowBuilder'

export const initialState: WorkflowBuilderState = {
  nodes: INITIAL_NODES,
  edges: INITIAL_EDGES,
  currentMode: 'sequential',
  lastWorkflowId: undefined,
  savedViewport: null,
  currentRun: null,
  isRunning: false,
  loadedWorkflow: null,
  history: {
    past: [],
    future: [],
  },
  manualModeEnabled: false,
  currentPartialRunId: null,
  executedStepNodeIds: [],
  availableRuns: [],
  selectedRunIds: {},
  savingStatus: SavingStatus.Idle,
  selectedNodeId: null,
  // WebSocket state
  wsConnectionStatus: 'disconnected',
  activeNodeId: null,
  rightPanelTab: 'config',
  showExecutionPanel: false,
  pendingValidation: null,
  outputDisplayMode: OutputDisplayMode.Panel,
  batchRun: {
    isActive: false,
    batchId: null,
    workflowId: null,
    latestRunIsBatch: false,
    dismissedBatchId: null,
    totalFiles: 0,
    completedCount: 0,
    failedCount: 0,
    currentIndex: 0,
    fileStatuses: [],
    runsById: {},
    activeNodeIds: {},
    selectedRunId: null,
  },
}
